In [7]:
import pandas as pd

In [8]:
df=pd.read_csv(r"C:\Users\Admin\Documents\customer_shopping_behavior.csv")

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
df.shape

(3900, 18)

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [12]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [13]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [14]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df= df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [16]:
df.head

<bound method NDFrame.head of       customer_id  age  gender item_purchased     category  purchase_amount  \
0               1   55    Male         Blouse     Clothing               53
1               2   19    Male        Sweater     Clothing               64
2               3   50    Male          Jeans     Clothing               73
3               4   21    Male        Sandals     Footwear               90
4               5   45    Male         Blouse     Clothing               49
...           ...  ...     ...            ...          ...              ...
3895         3896   40  Female         Hoodie     Clothing               28
3896         3897   52  Female       Backpack  Accessories               49
3897         3898   46  Female           Belt  Accessories               33
3898         3899   44  Female          Shoes     Footwear               77
3899         3900   52  Female        Handbag  Accessories               81

           location size      color  season  review_rating  \
0          Kentucky    L       Gray  Winter            3.1
1             Maine    L     Maroon  Winter            3.1
2     Massachusetts    S     Maroon  Spring            3.1
3      Rhode Island    M     Maroon  Spring            3.5
4            Oregon    M  Turquoise  Spring            2.7
...             ...  ...        ...     ...            ...
3895       Virginia    L  Turquoise  Summer            4.2
3896           Iowa    L      White  Spring            4.5
3897     New Jersey    L      Green  Spring            2.9
3898      Minnesota    S      Brown  Summer            3.8
3899     California    M      Beige  Spring            3.1

     subscription_status   shipping_type discount_applied promo_code_used  \
0                    Yes         Express              Yes             Yes
1                    Yes         Express              Yes             Yes
2                    Yes   Free Shipping              Yes             Yes
3                    Yes    Next Day Air              Yes             Yes
4                    Yes   Free Shipping              Yes             Yes
...                  ...             ...              ...             ...
3895                  No  2-Day Shipping               No              No
3896                  No    Store Pickup               No              No
3897                  No        Standard               No              No
3898                  No         Express               No              No
3899                  No    Store Pickup               No              No

      previous_purchases payment_method frequency_of_purchases
0                     14          Venmo            Fortnightly
1                      2           Cash            Fortnightly
2                     23    Credit Card                 Weekly
3                     49         PayPal                 Weekly
4                     31         PayPal               Annually
...                  ...            ...                    ...
3895                  32          Venmo                 Weekly
3896                  41  Bank Transfer              Bi-Weekly
3897                  24          Venmo              Quarterly
3898                  24          Venmo                 Weekly
3899                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [ ]:
#create a  column age_group
labels = ['Young Adult','Adult','Middle_aged','Senior']
df['age_group']= pd.qcut(df['age'],q=4,labels=labels)

In [ ]:
df.columns

In [ ]:
df[['age', 'age_group']].head(10)

In [ ]:
#create column purchase frequency days 
frequency_mapping ={
    'Fortnightly': 14,
    'Weekly' :7,
    'Monthly' :30,
    'Quaterly':90,
    'Bi-weekly' :14,
    'Annually':365,
    'Every 3 months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

KeyError: "['purchase_frequency_days'] not in index"

In [18]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [19]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [20]:
df =df.drop('promo_code_used',axis=1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [22]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (2.0.41)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
from sqlalchemy import create_engine
username = "root"
password = "1234"
host = "127.0.0.1"
port = "3306"       # Default MySQL port
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://root:1234@127.0.0.1:3306/customer_behaviour")
try:
    with engine.connect() as connection:
        print("Connected to MySQL successfully!")
except Exception as e:
    print(f"Error connecting to database: {e}")

Connected to MySQL successfully!

In [24]:
df.to_sql('customer_shopping_behavior', con=engine, if_exists='replace', index=False)

3900

In [1]:
import os

In [2]:
print(os.getcwd())

C:\Users\Admin